### ISSUE TITLE
Anime y juegos 

### ISSUE THREAD

**Issue by ArielGuerra** [pdepjm/2023-tp0-presentacion-ZoeDominguez#1]
Yo también soy de zona Oeste, tomas el tren Sarmiento también?  ;(
Que animes viste? y también jugaba al COD cuando tenia tiempo

**Comment by ZoeDominguez** [comment]
Sii, viajo en el Sarmiento, desde Moreno. Es un mar de gente a la mañana.
Animes completos vi varios, Katekyo Hitman Reborn, Bleach (espero su próxima temporada), D-gray Man, Inuyasha, High School of the Dead, Zombie Loan, 11 eyes

**Comment by ArielGuerra** [comment]
jaja si es un quilombo y mas que no funciona 5 de cada 4 veces que viajo. Yo soy de Padua.
bonísimos, alguno que otro están es mis pendientes :D
