### ISSUE TITLE
Mahwas de reencarnacion

### ISSUE THREAD

**Issue by Agustoledo10** [pdepjm/2023-tp0-presentacion-ZoeDominguez#2]
Buenass, lei que pusiste manhwas de reencarnacion y me hiciste acordar a TBATE (The beginning After the End) que me parecio aaalto mahwa, me lo lei al toque jajaj, lo leiste? Y sino cuales estabas leyendo y me recomendas?

**Comment by ZoeDominguez** [comment]
Hola, ese lo leí pero lo dejé. Los que estoy leyendo ahora son Las clases S que crié, Lector Omnisciente (que si bien el MC no reencarna, el protagonista original sí), varios de romance, Debut or Die, hay varios que dejé en el camino pero que posiblemente retome, como el mago de los 8 círculo (creo que así se llama)
