### ISSUE TITLE
mobile legends

### ISSUE THREAD

**Issue by fwahid16** [pdepjm/2023-tp0-presentacion-ZoeDominguez#3]
buenass, Cuáles son tus main en el mobile?(los míos son dyroth, khaled y angela)

**Comment by ZoeDominguez** [comment]
Holaa, soy Main Ruby (la uso en Exp y Tank) y Nana (se me hace divertido el bichito), aunque ando usando más a Kagura

**Comment by fwahid16** [comment]
intenté aprender Ruby(AD) pero no tenía suficiente daño, igual hace rato que no juego no se si nerfearon a mis main
