### ISSUE TITLE
Cod y smash

### ISSUE THREAD

**Issue by tomasfiestas** [pdepjm/2023-tp0-presentacion-ZoeDominguez#4]
Banco una locura esos dos juegos, sobretodo el smash porque no se ve gente de ahi todos los dias jajajaj.
En el cod vas a zombies o solo multi?

**Comment by ZoeDominguez** [comment]
El smash es parte de mi infancia, con los juegos Friv, en la Nintendo me re salvo cuando me fui de viaje, lo jugaba con mi hermano, al pobre le spameaba el martillo de Kirby.
El Cod voy a veces multi, mi favorito es el Black Ops 2, el modo zombie lo juego cuando estoy con familia o amigos, pero lo dejé un poco de lado por la facultad

**Comment by tomasfiestas** [comment]
jajajajaj entre el martillo de kirby y meta knight no se cual era el mas odiable, pero banco ganar es ganar no importa que tan asqueroso se sea. Y claroooo, el black ops 2 es mitico, yo te recomendaria darle una chance a zombies que tiene los easter eggs que son un 10 aunque son bastante dificiles
