### ISSUE TITLE
Smash

### ISSUE THREAD

**Issue by Valen-Pino** [pdepjm/2023-tp0-presentacion-ZoeDominguez#6]
Jajja cuál es tu main en Smash? Tenés otros juegos en la switch?

**Comment by ZoeDominguez** [comment]
Main Kirby (aguante spamear el martillo) y Bayonetta.
Otros juegos, el Zelda, 2 de Pokemon y el Animal Crossing

**Comment by EZEarroyo** [comment]
Yo jugaba mucho Animal Crossing,hasta que se me cayo la switch a la pileta.
Lo se,soy un boludo.

**Comment by ZoeDominguez** [comment]
¿Cómo hiciste? Necesito el contexto de la desgracia
